ERROR - 2021-03-26 05:11:59 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:11:59 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', true)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:11:59 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:13:39 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:13:39 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', true)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:13:39 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:18:21 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:18:21 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', false)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:18:21 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:20:10 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:20:10 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', false)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:20:10 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:20:13 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:20:13 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', false)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:20:13 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:24:06 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:24:06 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', false)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:24:06 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:24:51 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:24:52 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', true)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:24:52 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:26:35 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:26:35 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', true)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:26:35 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:26:36 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:26:36 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', true)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:26:36 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:26:44 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:26:44 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', true)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:26:44 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:28:38 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:28:38 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('admin', '"heslo"', false)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:28:38 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-03-26 05:30:05 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-03-26 05:30:05 --> Unable to connect to the database.
#0 C:\xampp\htdocs\autoservis\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\autoservis\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#2 C:\xampp\htdocs\autoservis\ion-auth\Models\IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#3 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#4 C:\xampp\htdocs\autoservis\ion-auth\Libraries\IonAuth.php(104): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\autoservis\ion-auth\Controllers\Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): IonAuth\Controllers\Auth->login()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#8 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-03-26 05:30:05 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\autoservis\app\Views\errors\html\error_exception.php(100): print_r(Object(IonAuth\Controllers\Auth), true)
#2 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\autoservis\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-03-26 08:29:37 --> Undefined property: App\Controllers\HlavniStrana::$load
#0 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 19, Array)
#1 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#3 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-03-26 08:57:58 --> Class 'App\Controllers\Hlavni_Model' not found
#0 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#1 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-03-26 08:58:50 --> Class 'App\Controllers\Hlavni_Model' not found
#0 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#1 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-03-26 09:01:17 --> Class 'BaseController' not found
#0 C:\xampp\htdocs\autoservis\system\Autoloader\Autoloader.php(294): include_once()
#1 C:\xampp\htdocs\autoservis\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#4 [internal function]: spl_autoload_call('App\\Controllers...')
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(893): class_exists('\\App\\Controller...', true)
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(417): CodeIgniter\CodeIgniter->startController()
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:01:23 --> Class 'BaseController' not found
#0 C:\xampp\htdocs\autoservis\system\Router\Router.php(562): include_once()
#1 C:\xampp\htdocs\autoservis\system\Router\Router.php(170): CodeIgniter\Router\Router->autoRoute('Hlavnistrana')
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(816): CodeIgniter\Router\Router->handle('Hlavnistrana')
#3 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(385): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#4 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-03-26 09:01:30 --> Class 'App\Controllers\Hlavni_Model' not found
#0 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#1 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-03-26 09:01:56 --> Trying to get property 'vyrobce' of non-object
#0 C:\xampp\htdocs\autoservis\app\Views\pages\vypis_aut.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/vypis_aut', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(27): view('pages/vypis_aut', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:03:29 --> Trying to get property 'vyrobce' of non-object
#0 C:\xampp\htdocs\autoservis\app\Views\pages\vypis_aut.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/vypis_aut', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(27): view('pages/vypis_aut', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:03:30 --> Trying to get property 'vyrobce' of non-object
#0 C:\xampp\htdocs\autoservis\app\Views\pages\vypis_aut.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/vypis_aut', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(27): view('pages/vypis_aut', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:03:31 --> Trying to get property 'vyrobce' of non-object
#0 C:\xampp\htdocs\autoservis\app\Views\pages\vypis_aut.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/vypis_aut', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(27): view('pages/vypis_aut', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:03:31 --> Trying to get property 'vyrobce' of non-object
#0 C:\xampp\htdocs\autoservis\app\Views\pages\vypis_aut.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/vypis_aut', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(27): view('pages/vypis_aut', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:03:31 --> Trying to get property 'vyrobce' of non-object
#0 C:\xampp\htdocs\autoservis\app\Views\pages\vypis_aut.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/vypis_aut', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(27): view('pages/vypis_aut', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:14:32 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\autoservis\system\Model.php(615): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\autoservis\system\Model.php(205): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\autoservis\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(0, 0)
#3 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(23): CodeIgniter\BaseModel->findAll()
#4 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisAut()
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-03-26 09:22:45 --> Class 'App\Controllers\Model_zamestnanci' not found
#0 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisZamestnancu()
#1 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-03-26 09:23:07 --> Undefined variable: zamestnanci
#0 C:\xampp\htdocs\autoservis\app\Views\pages\zamestnanci.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/zamestnan...', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(38): view('pages/zamestnan...', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisZamestnancu()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:23:20 --> Undefined index: osobni_cislo
#0 C:\xampp\htdocs\autoservis\app\Views\pages\zamestnanci.php(31): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 31, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/zamestnan...', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(38): view('pages/zamestnan...', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisZamestnancu()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-03-26 09:26:58 --> Class 'App\Controllers\Model_dily' not found
#0 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisDilu()
#1 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#2 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-03-26 09:31:33 --> Undefined variable: zakaznici
#0 C:\xampp\htdocs\autoservis\app\Views\pages\zakaznici.php(23): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 23, Array)
#1 C:\xampp\htdocs\autoservis\system\View\View.php(220): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\autoservis\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\autoservis\system\Common.php(1217): CodeIgniter\View\View->render('pages/zakaznici', Array, true)
#4 C:\xampp\htdocs\autoservis\app\Controllers\HlavniStrana.php(60): view('pages/zakaznici', Array)
#5 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(936): App\Controllers\HlavniStrana->vypisZakazniku()
#6 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\HlavniStrana))
#7 C:\xampp\htdocs\autoservis\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\autoservis\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
